packages:
  - "crates/xlsx-node"
minimumReleaseAgeExclude:
  - '@maleus/xlsx-reader-darwin-arm64@0.1.0'
  - '@maleus/xlsx-reader-linux-arm64-gnu@0.1.0'
  - '@maleus/xlsx-reader-linux-arm64-musl@0.1.0'
  - '@maleus/xlsx-reader-linux-x64-gnu@0.1.0'
  - '@maleus/xlsx-reader-linux-x64-musl@0.1.0'
