/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A cursor over one worksheet.
 *
 * Single-consumer: the JavaScript facade is what drives it, one pull at a time.
 * Two overlapping `nextBatch` calls are serialised rather than interleaved, but
 * which of the two gets which batch is not defined.
 */
export declare class XlsxCursor {
  /** Build a cursor. Does no I/O: the file is opened on the first pull. */
  constructor(path: string, options: JsReaderOptions)
  /** The sheets the workbook declares. */
  sheets(): Promise<Array<JsSheetInfo>>
  /** Pull at most `size` rows. Resolves to `null` once the sheet is finished. */
  nextBatch(size: number): Promise<Array<Array<string | number | boolean | null>> | null>
  /**
   * Release the archive now rather than at the next garbage collection.
   *
   * A consumer that stops half way through an import — a validation failure
   * on row three — would otherwise hold two descriptors open for as long as
   * the object lives.
   */
  close(): void
}

/** Options for a listing, which reads no row and so needs no row budget. */
export interface JsListOptions {
  /** Bytes the archive may expand to. */
  maxDecompressedBytes: number
}

/**
 * Reader options. Both budgets are required — see the crate's decision on why
 * there is no permissive default.
 */
export interface JsReaderOptions {
  /** Sheet to read. Defaults to the first one in the workbook. */
  sheet?: string
  /** Bytes the archive may expand to, every entry counted. */
  maxDecompressedBytes: number
  /** Rows the sheet may yield, header row included. */
  maxRows: number
}

/** One sheet, as the workbook declares it. */
export interface JsSheetInfo {
  /** Sheet name, as it appears on the tab. */
  name: string
  /** `false` for both `hidden` and `veryHidden` sheets. */
  visible: boolean
}

/**
 * List the sheets a workbook declares, without opening it to read rows.
 *
 * Separate from [`XlsxCursor::sheets`] because it takes a different path
 * through the file: two small parts inflated and counted, rather than a walk of
 * the whole archive. The bound still applies — it is applied to what gets read.
 */
export declare function listSheets(path: string, options: JsListOptions): Promise<Array<JsSheetInfo>>
