/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A cursor over one worksheet.
 *
 * Single-consumer: the JavaScript facade is what drives it, one pull at a time.
 * Two overlapping `nextBatch` calls are serialised rather than interleaved, but
 * which of the two gets which batch is not defined.
 */
export declare class XlsxCursor {
  /** Build a cursor. Does no I/O: the file is opened on the first pull. */
  constructor(path: string, options: JsReaderOptions)
  /** The sheets the workbook declares. */
  sheets(): Promise<Array<JsSheetInfo>>
  /** Pull at most `size` rows. Resolves to `null` once the sheet is finished. */
  nextBatch(size: number): Promise<Array<Array<string | number | boolean | null>> | null>
  /**
   * Release the archive now rather than at the next garbage collection.
   *
   * A consumer that stops half way through an import — a validation failure
   * on row three — would otherwise hold two descriptors open for as long as
   * the object lives.
   */
  close(): void
}

/**
 * A worksheet being written, one batch of rows at a time.
 *
 * Two phases, and the split is a property of the format rather than a choice:
 * rows go to a spill file as they arrive, and the archive is assembled from
 * those files at the end. Nothing reaches the consumer until [`Self::next_chunk`]
 * is called for the first time.
 */
export declare class XlsxSink {
  /** Open a workbook. Does no I/O beyond preparing the spill directory. */
  constructor(options: JsWriterOptions)
  /**
   * Append rows. Resolves when they are on the spill file.
   *
   * Rows cross by the batch for the same reason they do coming the other
   * way: one FFI call per row over a million rows costs more than the work.
   */
  writeRows(rows: Array<Array<JsCell>>, dateColumns: Array<number>): Promise<void>
  /**
   * Pull the next piece of the file. Resolves to `null` once it is complete.
   *
   * The first call starts the assembly on a thread of its own — deliberately
   * not one of the libuv pool's, which a save lasting seconds would occupy
   * to the exclusion of every other asynchronous file operation in the
   * process. What does briefly occupy a pool thread is the wait for each
   * chunk, measured at about 4 ms across a full sheet.
   */
  nextChunk(): Promise<Buffer | null>
  /**
   * Abandon the workbook and release the spill file now.
   *
   * A consumer that gives up half way through an export — a broken socket on
   * row three — would otherwise leave the writing thread assembling an
   * archive nobody will read, and the spill file on disk until it finished.
   * The sink the thread writes into refuses the next chunk once this is set,
   * which unwinds the save.
   */
  close(): void
}

/** Options for a listing, which reads no row and so needs no row budget. */
export interface JsListOptions {
  /** Bytes the archive may expand to. */
  maxDecompressedBytes: number
}

/**
 * Reader options. Both budgets are required — see the crate's decision on why
 * there is no permissive default.
 */
export interface JsReaderOptions {
  /** Sheet to read. Defaults to the first one in the workbook. */
  sheet?: string
  /** Bytes the archive may expand to, every entry counted. */
  maxDecompressedBytes: number
  /** Rows the sheet may yield, header row included. */
  maxRows: number
}

/** One sheet, as the workbook declares it. */
export interface JsSheetInfo {
  /** Sheet name, as it appears on the tab. */
  name: string
  /** `false` for both `hidden` and `veryHidden` sheets. */
  visible: boolean
}

/**
 * How the workbook is set up. Mirrors [`JsReaderOptions`] in shape: plain
 * data, validated at the boundary.
 */
export interface JsWriterOptions {
  /** Name on the sheet tab. At most 31 characters, free of `[ ] : * ? / \`. */
  sheetName: string
  /**
   * Column indices whose strings are ISO 8601 timestamps.
   *
   * Date-ness cannot be guessed from a value: `"2024-03-25"` is a perfectly
   * good piece of text, and a reader that decided otherwise would turn a
   * product reference into a day. It cannot be guessed from a JavaScript
   * `Date` either without calling `toISOString` once per cell across the
   * boundary, which is the cost this design exists to avoid. So it is
   * declared once, for the column, and the facade is what turns a `columns`
   * declaration into this list.
   */
  dateColumns: Array<number>
  /**
   * Where the row spill files go. `None` uses the platform temporary
   * directory.
   */
  tempDir?: string
}

/**
 * List the sheets a workbook declares, without opening it to read rows.
 *
 * Separate from [`XlsxCursor::sheets`] because it takes a different path
 * through the file: two small parts inflated and counted, rather than a walk of
 * the whole archive. The bound still applies — it is applied to what gets read.
 */
export declare function listSheets(path: string, options: JsListOptions): Promise<Array<JsSheetInfo>>
